# =============================================
# SonarQube Project Configuration - Auth SVC
# =============================================

# Identitas Project — harus sama dengan di Jenkinsfile
sonar.projectKey=auth-svc
sonar.projectName=Auth Service
sonar.projectVersion=1.0

# Source code yang dianalisis
sonar.sources=.

# Folder/file yang dikecualikan dari analisis
sonar.exclusions=\
    **/node_modules/**, \
    **/*.test.js, \
    **/*.spec.js, \
    **/coverage/**, \
    **/dist/**, \
    **/.git/**

# Bahasa yang digunakan
sonar.language=js

# Encoding file
sonar.sourceEncoding=UTF-8

# Coverage report (jika pakai Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Test file location
sonar.test.inclusions=**/*.test.js,**/*.spec.js
